import React, { useState, useEffect } from 'react';
import { useGetDallEImageQuery } from "./dallEApiSlice";
import PulseLoader from 'react-spinners/PulseLoader'
import { useNavigate } from "react-router-dom";
import useTitle from "../../hooks/useTitle";

const DallE = () => {
  useTitle("Dall-E");
  const [prompt, setPrompt] = useState('');
  const [imageUrl, setImageUrl] = useState('');
  const [send, setSend] = useState('');
  const navigate = useNavigate();


  const handlePromptChange = (event) => {
    setPrompt(event.target.value);
  };

  const { data: image, error,isError } = useGetDallEImageQuery(send);

  const handleSubmit = (event) => {
    event.preventDefault();
      setImageUrl('');
      setSend(prompt);
      
  };

  useEffect(() => {
    if (image) {
      setImageUrl(image.url);
    }
  }, [image]);

  


  const handleKeyPress = (event) => {
    if (event.key === 'Enter') {
      handleSubmit(event);
    }
  };

  return (
    <div className="dalle-container">
       <button
            className="navigate-button-DallE"
            onClick={() => navigate("/chat")}
          >
            ChatGPT
          </button>
      <h1 className="dalle-title">DALL-E Image Generation</h1>
      <form className="dalle-form" onSubmit={handleSubmit}>
        <input
          className="dalle-input"
          type="text"
          value={prompt}
          onChange={handlePromptChange}
          onKeyDown={handleKeyPress}
          placeholder="Enter a prompt"
        />
        {send && isError && <div className="dalle-error">Error: {error.data.message}</div>}
        <button className="dalle-submit" type="submit" >
          Generate Image
        </button>
        {!imageUrl && send &&   <PulseLoader className="custom-loader" size={25} margin={25} color={'#FFF'} />}
      </form>
      {imageUrl && <img className="dalle-image" src={imageUrl} alt="Generated by DALL-E" />}
    </div>
  );
};

export default DallE;